### ISSUE TITLE
Over compilcated

### ISSUE THREAD

**Issue by sionsmith** [vdesabou/kafka-docker-playground#5632]
This was a brilliant resource which you could run on any enterprise laptop! NOW you have over complicated this by introducing a CLI too. Its a playground, why on earth would you think its a good idea to need a CLI tool to now run a playground setup?

**Comment by vdesabou** [comment]
Not sure why you're incredibly rude..I don't even feel like a should discuss with you as I really not appreciate your tone

Why having a CLI is an issue for you ? You should still be able to launch examples without the CLI

Is that because Bash version 4 is required ?

I will not discuss the usefulness of CLI, if you do not see the point, it's clearly that you have not used it (or you're just trolling). In any cases, that is a game changer for all people I know using the playground everyday, including myself, and there is no way I change that or regret this decision.

**Comment by vdesabou** [comment]
2. This comes from [bashly](https://bashly.dannyb.co/installation/#prerequisites) i use to generate the CLI.
Bash 4 was released in 2009, shame is on Apple to release such old version


Closing the ticket
